### ISSUE TITLE
Regex causes generation issues

### ISSUE THREAD

**Issue by lfvJonas** [Luftfartsverket/openapi-to-asciidoc#25]
### Bug Report: Incorrect Table Formatting When Regex Pattern Contains `|` Character

**Description:**

When using `openapi-to-asciidoc`, a regex defined in the OpenAPI specification using the `pattern` field that includes the `|` character (e.g., `foo|bar`) is incorrectly rendered in the AsciiDoc output. Specifically, if the regex appears in a table (e.g., within schema details), AsciiDoc interprets the `|` character as a column separator, resulting in broken table formatting.

**Steps to Reproduce:**

1. Define an OpenAPI schema like the following:

   ```yaml
   components:
     schemas:
       Example:
         type: object
         properties:
           exampleField:
             type: string
             pattern: 'foo|bar'
   ```

2. Use `openapi-to-asciidoc` to generate documentation.

3. Check the resulting AsciiDoc table where this pattern is rendered.

**Expected Behavior:**

The pattern string `foo|bar` should be displayed as-is within a single table cell, with the `|` character preserved and not interpreted as a column delimiter.

**Actual Behavior:**

The AsciiDoc output renders the `|` as a column separator, which breaks the regex string across multiple columns and corrupts the table layout.

**Suggested Fix:**

Update the rendering logic to:
- Escape the `|` character in AsciiDoc output (e.g., `\|`)
- Or wrap the pattern in backticks or another inline literal format to prevent parsing as table syntax

**Additional Context:**

This issue can mislead readers by misrepresenting regex patterns in the documentation, especially when used for validation in API schemas.
